uploads = []
outputs = []

[[generated]]
id = "QMq1oSyX8nweootwFhRto"
uri = "file://artifacts/pitch-perfect/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5y1J5KWexQqXgnKt5tul_"
uri = "file://artifacts/pitch-perfect/assets/images/stadium.png"
type = "image"
title = "generated_image"

[[generated]]
id = "IoT07ubf2jGhkTvbC7P9M"
uri = "file://artifacts/pitch-perfect/assets/images/batter_1.png"
type = "image"
title = "batter-red-facing-camera"

[[generated]]
id = "P9PwEpAUyY9awYDZ1a2Jt"
uri = "file://artifacts/pitch-perfect/assets/images/batter_2.png"
type = "image"
title = "batter-navy-lefty-facing"

[[generated]]
id = "8RG1ziIV6WIbzGdzgNSew"
uri = "file://artifacts/pitch-perfect/assets/images/batter_3.png"
type = "image"
title = "batter-black-green-facing"
