uploads = []

[[generated]]
id = "QMq1oSyX8nweootwFhRto"
uri = "file://artifacts/pitch-perfect/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "5y1J5KWexQqXgnKt5tul_"
uri = "file://artifacts/pitch-perfect/assets/images/stadium.png"
type = "image"
title = "generated_image"

[[generated]]
id = "IoT07ubf2jGhkTvbC7P9M"
uri = "file://artifacts/pitch-perfect/assets/images/batter_1.png"
type = "image"
title = "batter-red-swing-sideangle"

[[generated]]
id = "P9PwEpAUyY9awYDZ1a2Jt"
uri = "file://artifacts/pitch-perfect/assets/images/batter_2.png"
type = "image"
title = "batter-navy-swing-load"

[[generated]]
id = "8RG1ziIV6WIbzGdzgNSew"
uri = "file://artifacts/pitch-perfect/assets/images/batter_3.png"
type = "image"
title = "batter-black-swing-load"

[[generated]]
id = "ckYcqM2Oe5gr12pPyIwvr"
uri = "file://attached_assets/generated_images/pp_icon_a.png"
type = "image"
title = "pitch perfect icon a"

[[generated]]
id = "Oia2te21gWhyvT9v6P7Va"
uri = "file://attached_assets/generated_images/pp_icon_b.png"
type = "image"
title = "pitch perfect icon b"

[[generated]]
id = "avweud4mZmOv8ChCSpeIL"
uri = "file://attached_assets/generated_images/pp_icon_c.png"
type = "image"
title = "pitch perfect icon c"

[[generated]]
id = "myms9mDU5Zu-gMSj4Quvp"
uri = "file://attached_assets/generated_images/pp_icon_mir_a.png"
type = "image"
title = "pp icon mirrored a"

[[generated]]
id = "XlRA_bIlN1ahpcU6mEzV6"
uri = "file://attached_assets/generated_images/pp_icon_mir_b.png"
type = "image"
title = "pp icon mirrored b"

[[generated]]
id = "nwryWZmGhNhIBKYQ_zBh9"
uri = "file://attached_assets/generated_images/pp_icon_mir_c.png"
type = "image"
title = "pp icon mirrored c"

[[generated]]
id = "XK8WPAqgHz_UEuVOg5Rjq"
uri = "file://attached_assets/generated_images/pp_icon_a1.png"
type = "image"
title = "pp icon a1"

[[generated]]
id = "uKwomr32_723v-U0dP_9O"
uri = "file://attached_assets/generated_images/pp_icon_a2.png"
type = "image"
title = "pp icon a2"

[[generated]]
id = "-kr6oTjdEL_lrr-Jnihsw"
uri = "file://attached_assets/generated_images/pp_icon_a3.png"
type = "image"
title = "pp icon a3"

[[outputs]]
id = "x07VhkfH3oS9cBXWD0mp1"
uri = "file://attached_assets/generated_audio/sound_effect_pp_throw.mp3"
type = "audio"
title = "pp_throw"

[[outputs]]
id = "FLcnvZQJgRr5oP66DdN3a"
uri = "file://attached_assets/generated_audio/sound_effect_pp_mitt.mp3"
type = "audio"
title = "pp_mitt"

[[outputs]]
id = "o4ri453A9-H9ZIo9h1zPt"
uri = "file://attached_assets/generated_audio/sound_effect_pp_cheer.mp3"
type = "audio"
title = "pp_cheer"

[[outputs]]
id = "myMFGVWvgHSCVLE4HSo2u"
uri = "file://attached_assets/generated_audio/sound_effect_pp_hit.mp3"
type = "audio"
title = "pp_hit"

[[outputs]]
id = "bHUqfFC_Xw0AzcUV3wb3w"
uri = "file://attached_assets/generated_audio/music_pitchperfect_bgm.mp3"
type = "audio"
title = "pitchperfect_bgm"

[[outputs]]
id = "kPFDeVxNhuT2EBAiHkC-x"
uri = "file://attached_assets/generated_audio/sound_effect_pp_tap.mp3"
type = "audio"
title = "pp_tap"

[[outputs]]
id = "mlA38TRmyv3wXBvhhD2uc"
uri = "file://attached_assets/generated_audio/ump_ball.mp3"
type = "audio"
title = "ump ball"

[[outputs]]
id = "gZ-JzwHyK1wkrrnFczyw9"
uri = "file://attached_assets/generated_audio/ump_strike2.mp3"
type = "audio"
title = "ump strike two"

[[outputs]]
id = "VdVstCWW9I2oJVoiATP5i"
uri = "file://attached_assets/generated_audio/ump_strike1.mp3"
type = "audio"
title = "ump strike one"

[[outputs]]
id = "yXnLjS_bbimT6Fsz0Eabi"
uri = "file://attached_assets/generated_audio/ump_strikeout.mp3"
type = "audio"
title = "ump strikeout"

[[outputs]]
id = "Ay71SKLQYzP6BiaK1s-MO"
uri = "file://attached_assets/generated_audio/boo.mp3"
type = "audio"
title = "crowd boos"
